In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(arr.shape)
print(matrix.shape)

(5,)
(3, 3)


In [ ]:
print(arr.ndim) 
print(matrix.ndim)

1
2


In [8]:
print(arr.dtype)

int64


In [10]:
arr = np.array([1,  2, 3, 4, 5, 6, 7, 8, 9])
matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [17]:
zero_array = np.zeros((3, 3))
zero_array4 = np.zeros((4, 4))
zero_array5 = np.zeros((5, 5))
one_array = np.ones((4,4))
identity_matrix = np.eye(5)
print(zero_array)
print(zero_array4)
print(zero_array5)
print(one_array)
print(identity_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
print(arr.shape)
print(matrix.shape)
print(zero_array.shape)
print(zero_array4.shape)
print(zero_array5.shape)
print(arr.ndim)
print(matrix.ndim)
print(zero_array.ndim)
print(zero_array4.ndim)
print(zero_array5.ndim)
print(arr.dtype)
print(matrix.dtype)
print(zero_array.dtype)
print(zero_array4.dtype)
print(zero_array5.dtype)
print(arr.size)
print(matrix.size)
print(zero_array.size)
print(zero_array4.size)
print(zero_array5.size)
print(one_array.size)
print(identity_matrix.size)
print(one_array.shape)
print(identity_matrix.shape)
print(one_array.ndim)
print(identity_matrix.ndim)
print(one_array.dtype)
print(identity_matrix.dtype)

(9,)
(5, 5)
(3, 3)
(4, 4)
(5, 5)
1
2
2
2
2
int64
float64
float64
float64
float64
9
25
9
16
25
16
25
(4, 4)
(5, 5)
2
2
float64
float64


In [ ]:
"""
What is NumPy?
NumPy is a python library that is used to perform numerical array operations.

Why is NumPy faster than lists?
it is faster than list because it uses less memory and is implemented in C and Fortran.

What is the difference between shape and ndim?
shape is used to get the size of each axis and ndim is used to get the number of axes of the array.

What  is dtype?
dtype is used to tell the type of the array. whether it is int, float, bool, etc."""

'\nWhat is NumPy?\nNumPy is a python library that is used to perform numerical array operations.\n\nWhy is NumPy faster than lists?\nit is faster than list because it uses less memory and is implemented in C and Fortran.\n\nWhat is the difference between shape and ndim?\nshape is used to get the dimensions of the array and ndim is used to get the number of dimensions of the array.\n\nWhat  is dtype?\ndtype is used to tell the type of the array. whether it is int, float, bool, etc.'

In [ ]:
""" Key Takeaways

- NumPy is optimized for numerical computing.
- np.array() creates arrays.
- shape returns the size of each dimension.
- ndim returns the number of dimensions.
- dtype returns the element data type.
- size returns the total number of elements.
- np.zeros() creates an array filled with zeros.
- np.ones() creates an array filled with ones.
- np.eye() creates an identity matrix."""