In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr_1 = np.arange(5,15)
print(arr_1)

[ 5  6  7  8  9 10 11 12 13 14]


In [5]:
arr_2 = np.arange(1, 20, 2)
print(arr_2)

[ 1  3  5  7  9 11 13 15 17 19]


In [6]:
arr_3 = np.linspace(0, 1, 5)
print(arr_3)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
arr_4 = np.random.rand(3, 3)
print(arr_4)

[[0.38076974 0.1292937  0.96773277]
 [0.76192532 0.22675452 0.24467121]
 [0.90107197 0.24162028 0.41854443]]


In [8]:
arr_5 = np.random.randint(1, 100, size=(3,3))
print(arr_5)

[[67 58 76]
 [ 7 76 91]
 [44 97 26]]


In [9]:
arr_6 = np.array([10, 20, 30, 40, 50])
print(arr_6[0])
print(arr_6[-1])
print(arr_6[2])

10
50
30


In [10]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix[1,1])
print(matrix[2, 2])
print(matrix[0])
print(matrix[:,1])

5
9
[1 2 3]
[2 5 8]


In [15]:
arr_7 = np.arange(10)
print(arr_7[2:7])
print(arr_7[:5])
print(arr_7[5:])
print(arr_7[::-1])

[2 3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [19]:
arr_8 = np.arange(5)
arr_8[2] = 100
print(arr_8)
arr_8[1:4] = 50
print(arr_8)

[  0   1 100   3   4]
[ 0 50 50 50  4]


In [68]:
arr_9 = np.arange(5)
print(f"arr_9 {arr_9}")
view = arr_9[1:4]
view[0] = 999
print(f"view {view}")
copy = arr_9.copy()

copy[0] = -1

print(f"copy {copy}")
print(f"arr_9 {arr_9}")

arr_9 [0 1 2 3 4]
view [999   2   3]
copy [ -1 999   2   3   4]
arr_9 [  0 999   2   3   4]


In [28]:
arr_10 = np.arange(1,20)
arr_11 = np.arange(1,20,2)
arr_12 = np.linspace(0, 1, 10)
print(arr_10)
print(arr_11)
print(arr_12)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [39]:
matrix_1 = np.random.randint(100, size=(4,4))
print(matrix_1)
print(matrix_1.shape)
print(matrix_1.size)
print(matrix_1.dtype)

[[33 29 32 74]
 [84 39 39 45]
 [70  2 43 62]
 [82 40 76 96]]
(4, 4)
16
int32


In [51]:
matrix_2 = np.arange(1,17).reshape(4,4)
print(matrix_2)
print(matrix_2[0])
print(matrix_2[-1])
print(matrix_2[:,0])
print(matrix_2[:,-1])
print(matrix_2[1:3,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 2 3 4]
[13 14 15 16]
[ 1  5  9 13]
[ 4  8 12 16]
[[ 6  7]
 [10 11]]


In [56]:
matrix_2[1,:] = 100
print(matrix_2)
matrix_2[:,0] = -1
print(matrix_2)

[[ -1   2   3   4]
 [100 100 100 100]
 [ -1  10  11  12]
 [ -1  14  15  16]]
[[ -1   2   3   4]
 [ -1 100 100 100]
 [ -1  10  11  12]
 [ -1  14  15  16]]


In [ ]:
"""
Difference between arange() and linspace().
arange() is used to assign values to arrays where as linspace is used to assign gaps while assigning values
Difference between indexing and slicing.
indexing is providing index to all the values inside the arrays while slicing is used to extract a particular part in the arrays
Slicing extracts a subset of an array without copying the data by default.
Why is NumPy indexing faster than Python lists?
numpy is based on c and fotran which has faster execution time whereas python lists are based on standard pyhton and has higher computation time
Difference between a view and a copy.
dont know
Why is .copy() important?
dont know
"""

'\nDifference between arange() and linspace().\narange() is used to assign values to arrays where as linspace is used to assign gaps while assigning values\nDifference between indexing and slicing.\nindexing is providing index to all the values inside the arrays while slicing is used to extract a particular part in the arrays\nWhy is NumPy indexing faster than Python lists?\nnumpy is based on c and fotran which has faster execution time whereas python lists are based on standard pyhton and has higher computation time\nDifference between a view and a copy.\ndont know\nWhy is .copy() important?\ndont know\n'

In [58]:
"""
import numpy as np

arr = np.arange(10)

a = arr[2:6]

a[:] = 100

print(arr)
Will arr change?why?
no because the values  in arr are not affected directly.
"""

'\nimport numpy as np\n\narr = np.arange(10)\n\na = arr[2:6]\n\na[:] = 100\n\nprint(arr)\nWill arr change?why?\nno because the values  in arr are not affected directly.\n'

In [ ]:
"""range() creates a range object mainly used for iteration, whereas np.arange() creates a NumPy array for numerical computation."""