In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b) #[5, 7, 9]
print(a - b) #[-3, -3, -3]
print(a * b) #[4, 10, 18]
print(a / b) #[0.25, 0.4, 0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
arr = np.array([10,20,30])

print(arr + 5)
print(arr - 5)
print(arr * 2)
print(arr / 10)
""" 
Why doesn't NumPy need a loop here?
numpy doesnt need a loop here because every elements in the numpy array will be treated the same and braodcasted the same operations. 
"""

[15 25 35]
[ 5 15 25]
[20 40 60]
[1. 2. 3.]


" \nWhy doesn't NumPy need a loop here?\nnumpy doesnt need a loop here because every elements in the numpy array will be treated the same.\n"

In [3]:
numbers = [1,2,3,4]

result = []

for n in numbers:
    result.append(n*2)

print(result)

[2, 4, 6, 8]


In [4]:
arr = np.array([1,2,3,4])

print(arr*2)

[2 4 6 8]


In [5]:
""" 
Why is NumPy faster?
numpy is faster because it is built on highly  efficient data structures written on c and fortran
"""

' \nWhy is NumPy faster?\nnumpy is faster because it is built on highly  efficient data structures written on c and fortran\n'

In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix + 10)
""" 
How does NumPy add 10 to every element without a loop?
numpy adds 10 to every element as it broadcasts the same operation on every element in the matrix
"""

[[11 12 13]
 [14 15 16]]


' \nHow does NumPy add 10 to every element without a loop?\nnumpy adds 10 to every element due to vectorization.\n'

In [28]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

row = np.array([10,20,30])

print(matrix + row)#error

[[11 22 33]
 [14 25 36]]


In [8]:
arr = np.array([4,9,16,25])

print(np.sqrt(arr))

[2. 3. 4. 5.]


In [27]:
arr = np.array([1,2,3])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
""" 
Which of these functions do you think are heavily used during EDA?
min, max, mean, sum
"""

6
2.0
3
1


' \nWhich of these functions do you think are heavily used during EDA?\nmin, max, mean, sum\n'

In [11]:
arr = np.array([10,20,30,40])

print(arr > 20)

[False False  True  True]


In [12]:
print(arr[arr>20])

[30 40]


In [13]:
a = np.array([2,4,6])
b = np.array([1,3,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


In [15]:
arr = np.array([5,10,15])
print(arr*3)

[15 30 45]


In [17]:
arr = np.arange(1,10)
arr = arr.reshape(3,3)
arr = arr + 100

In [21]:
arr = np.linspace(5,25,5)
print(arr[arr > 15])

[20. 25.]


In [26]:
""" 
What is vectorization?
vectorization is running operation on whole block of data at once rather than each element individually.

Why is NumPy faster than Python loops?
numpy is built upon c and fortran which makes it highly efficient.It is also faster because arrays store elements in contiguous memory,
 making operations more cache-friendly.

What is broadcasting?
NumPy automatically expands compatible arrays so arithmetic can be performed without manually copying data.

Difference between scalar operations and array operations?
scalar operation is applying operations on a single data element and array operations is applying the operation on all the elements of array at once

Why are NumPy mathematical functions preferred over writing loops?
it is faster due to vectorization.
"""

' \nWhat is vectorization?\nvectorization is running operation on whole block of data at once rather than each element individually.\n\nWhy is NumPy faster than Python loops?\nnumpy is built upon c and fortran which makes it highly efficient.It is also faster because arrays store elements in contiguous memory,\n making operations more cache-friendly.\n\nWhat is broadcasting?\nNumPy automatically expands compatible arrays so arithmetic can be performed without manually copying data.\n\nDifference between scalar operations and array operations?\nscalar operation is applying operations on a single data element and array operations is applying the operation on all the elements of array at once\n\nWhy are NumPy mathematical functions preferred over writing loops?\nit is faster due to vectorization.\n'

In [24]:
import numpy as np

arr = np.array([2,4,6])

print(arr + arr) #[4, 8, 12]

print(arr * arr) #[4,16,36]

print(arr > 3) #[False, True, True]

print(arr[arr > 3]) #[4, 6]

[ 4  8 12]
[ 4 16 36]
[False  True  True]
[4 6]
